//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tuote : IValidatableObject
    {
        [Required]
        public int TuoteID { get; set; }
        [Required]
        [StringLength(50)]
        public string Nimi { get; set; }
        [Required]
        public decimal Hinta { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Anna luku väliltä 0-100.")]
        public decimal Veroprosentti { get; set; }

        IEnumerable<ValidationResult> IValidatableObject.Validate(
          ValidationContext validationContext)
        {
            if (Hinta < 0)
            {
                yield return new ValidationResult("Anna positiivinen desimaaliluku hinnalle!");
            }
            if (TuoteID < 0)
            {
                yield return new ValidationResult("Anna positiivinen luku ID:lle!");
            }
        }

    }
}
